export const dummy_data = [
    { id: 1, name: 'John', age: 30, },
    { id: 2, name: 'Mary', age: 25 },
    { id: 3, name: 'Peter', age: 20 },
    { id: 4, name: 'Emily', age: 28 },
    { id: 5, name: 'Daniel', age: 32 },
    { id: 6, name: 'Sophia', age: 22 },
    { id: 7, name: 'David', age: 35 },
    { id: 8, name: 'Emma', age: 26 },
    { id: 9, name: 'Michael', age: 31 },
    { id: 10, name: 'Olivia', age: 24 },
    { id: 11, name: 'James', age: 27 },
    { id: 12, name: 'Ava', age: 29 },
    { id: 13, name: 'Christopher', age: 33 },
    { id: 14, name: 'Isabella', age: 23 },
    { id: 15, name: 'William', age: 30 },
    { id: 16, name: 'Abigail', age: 28 },
    { id: 17, name: 'Benjamin', age: 34 },
    { id: 18, name: 'Mia', age: 25 },
    { id: 19, name: 'Ethan', age: 26 },
    { id: 20, name: 'Charlotte', age: 27 },
    { id: 21, name: 'Alexander', age: 31 },
    { id: 22, name: 'Grace', age: 22 },
    { id: 23, name: 'Henry', age: 29 },
    { id: 24, name: 'Sophie', age: 33 },
    { id: 25, name: 'Liam', age: 24 },
    { id: 26, name: 'Chloe', age: 30 },
    { id: 27, name: 'Jackson', age: 35 },
    { id: 28, name: 'Ella', age: 28 },
    { id: 29, name: 'Lucas', age: 26 },
    { id: 30, name: 'Avery', age: 23 },
    { id: 31, name: 'Daniel', age: 32 },
    { id: 32, name: 'Madison', age: 31 },
    { id: 33, name: 'Logan', age: 27 },
    { id: 34, name: 'Aria', age: 29 },
    { id: 35, name: 'Jack', age: 30 },
    { id: 36, name: 'Scarlett', age: 25 },
    { id: 37, name: 'Ryan', age: 28 },
    { id: 38, name: 'Lily', age: 33 },
    { id: 39, name: 'Samuel', age: 26 },
    { id: 40, name: 'Penelope', age: 22 },
    { id: 41, name: 'Nathan', age: 34 },
    { id: 42, name: 'Grace', age: 23 },
    { id: 43, name: 'Dylan', age: 32 },
    { id: 44, name: 'Zoe', age: 27 },
    { id: 45, name: 'Carter', age: 30 },
    { id: 46, name: 'Lillian', age: 29 },
    { id: 47, name: 'Gabriel', age: 25 },
    { id: 48, name: 'Aubrey', age: 28 },
    { id: 49, name: 'Joseph', age: 31 },
    { id: 50, name: 'Hannah', age: 24 },
];


export const image='https://blog.hootsuite.com/wp-content/uploads/2020/02/Image-copyright-556x556.png.webp'
export const email="test@gmail.com" 